on:
  push:
    branches: [testing]
jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    steps:
      - uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          ACTIONS_NODE: ${{ secrets.ACTIONS_NODE }}
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
